apiVersion: v1
kind: Template
labels:
  template: frontend-backend-epg
metadata:
  annotations:
    description: Template for deploying Apache and MariaDB on RHEL with ACI EPG
    iconClass: icon-mysql-database
    tags: quickstart,oracle
  name: frontend-backend-epg
  namespace: openshift
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: ${NAME}-frontend
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}-frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}-frontend
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${NAME}-frontend
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}-frontend
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      description: Defines how to deploy the application server
      opflex.cisco.com/endpoint-group: '{"tenant":"mykube","app-profile":"kubernetes","name":"${EPG_FRONTEND}"}'
    name: frontend
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: frontend
          tier: frontend
      spec:
        containers:
        - name: aci-frontend
          image: docker-registry.default.svc:5000/openshift/frontend
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
          env:
          - name: GET_HOSTS_FROM
            value: dns
          ports:
          - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: backend
  spec:
    ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    selector:
      name: ${NAME}-backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}-backend
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      description: Defines how to deploy the application server
      opflex.cisco.com/endpoint-group: '{"tenant":"mykube","app-profile":"kubernetes","name":"${EPG_BACKEND}"}'
    name: backend
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: backend
          tier: backend
      spec:
        containers:
        - name: aci-frontend
          image: docker-registry.default.svc:5000/openshift/backend
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
          env:
          - name: GET_HOSTS_FROM
            value: dns
          ports:
          - containerPort: 3306
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  value: aci
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 1024Mi
- description: The exposed hostname that will route to the Application service, if
    left blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: The name of the EPG used in ACI for the Frontend, if left blank a value will be defaulted.
  displayName: Name of the Frontend EPG
  name: EPG_FRONTEND
  value: kube-default
- description: The name of the EPG used in ACI for the Backend, if left blank a value will be defaulted.
  displayName: Name of the Backend EPG
  name: EPG_BACKEND
  value: kube-default
